trigger: none

parameters:
  - name: ACTION
    type: string
    displayName: "Action"
    default: stop  # default for scheduled run
    values:
      - start
      - stop
  - name: RESOURCE_GROUP
    type: string
    default: "onefocus-rg"
  - name: SERVER_NAME
    type: string
    default: "onefocus-db"

schedules:
- cron: "0 1 * * *"  # 1:00 AM UTC
  displayName: "Stop PostgreSQL server at 1 AM"
  branches:
    include:
      - main
  always: true

- cron: "0 20 * * *" # 8:00 PM UTC
  displayName: "Start PostgreSQL server at 8 PM"
  branches:
    include:
      - main
  always: true

stages:
- stage: ManagePostgres
  displayName: "Manage PostgreSQL Flexible Server"
  jobs:
  - job: PostgreSQLServerScheduler
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Onefocus Service Connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Performing $ACTION on server $SERVER_NAME in resource group $RESOURCE_GROUP"

          if [ "$ACTION" == "start" ]; then
            az postgres flexible-server start --name $SERVER_NAME --resource-group $RESOURCE_GROUP
          elif [ "$ACTION" == "stop" ]; then
            az postgres flexible-server stop --name $SERVER_NAME --resource-group $RESOURCE_GROUP
          else
            echo "Invalid ACTION: $ACTION. Must be 'start' or 'stop'."
            exit 1
          fi
      env:
        ACTION: ${{ parameters.action }}
        RESOURCE_GROUP: ${{ parameters.RESOURCE_GROUP }}
        SERVER_NAME: ${{ parameters.SERVER_NAME }}