version: "3.8"
name: onefocusinfrastructure
services:
  opensearch:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=R6zntmydkm2?
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"   # OpenSearch API
      - "9600:9600"   # Performance Analyzer
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"   # UI
    depends_on:
      - opensearch

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - "5672:5672"      # AMQP
        - "15672:15672"    # Management UI
      environment:
        RABBITMQ_DEFAULT_USER: azureadministrator
        RABBITMQ_DEFAULT_PASS: R6zntmydkm2?
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "R6zntmydkm2?"]
    environment:
      REDIS_PASSWORD: "R6zntmydkm2?"
    volumes:
      - redis-data:/data

volumes:
  opensearch-data:
  rabbitmq-data:
  redis-data:
